export const hebrewCharMap = {
  "Aleph": "א",
  "Beth": "ב",
  "Gimel": "ג",
  "Daleth": "ד",
  "Heh": "ה",
  "Vav": "ו",
  "Zain": "ז",
  "Cheth": "ח",
  "Teth": "ט",
  "Yod": "י",
  "Kaph": "כ",
  "Lamed": "ל",
  "Mem": "מ",
  "Nun": "נ",
  "Samekh": "ס",
  "Ayin": "ע",
  "Peh": "פ",
  "Tzaddi": "צ",
  "Qoph": "ק",
  "Resh": "ר",
  "Shin": "ש",
  "Tav": "ת",
  "Kaph Finale": "ך",
  "Nun Finale": "ן",
  "Peh Finale": "ף",
  "Tzaddi Finale": "ץ"
};
